### ISSUE TITLE
"No placeholder found with name PH in message"

### ISSUE THREAD

**Issue by adwiens** [loclapp/locl#10]
I'm getting this error when loading JSON containing interpolations that was generated by "locl convert":

```
No placeholder found with name PH in message "msgId" ("Some Text {$INTERPOLATION}").
```

It seems "$INTERPOLATION" is incorrectly saved as "$PH" in the JSON. Example:

```
{
  "locale": "de-DE",
  "translations": {
    "msgId": "Some Text {$PH}"
  }
}
```

It works if I replace PH with INTERPOLATION.

Steps to reproduce:
1. Create an i18n element in a component's HTML that contains interpolation, e.g. `<p i18n="@@myId">Some Text {{ someProp }}</p>`
2. Extract XLF with ng xi18n command
3. Convert XLF to JSON with locl convert command
4. Load JSON in app with loadTranslations

Versions:
"@locl/core": "0.0.1-beta.2",
"@locl/cli": "0.0.1-beta.5",
Angular 9.0.0

**Comment by hrzwkstim01** [comment]
Same issue for me.

Versions:
"@locl/core": "0.0.1-beta.2",
"@locl/cli": "0.0.1-beta.5",
Angular 9.0.1

**Comment by ocombe** [comment]
Thanks for the report! Fixed in beta 6
