### ISSUE TITLE
Dynamic loaded translation translates only texts that is in the code but not in the html

### ISSUE THREAD

**Issue by shral** [loclapp/locl#13]
After loading the translation in the main.ts as it is in the documentation suggested (by writing `loadTranslations(data.translations as any)` instead of `loadTranslations(data as any)`), if I build my project without `--aot --prod` flags I can see all translations but if I build for production (with `--aot --prod` flags) I can see only the code translated texts (marked with $localized) translated.
[Hier](https://github.com/dcm4che/dcm4chee-arc-light/blob/master/dcm4chee-arc-ui2/src/main.ts) is how my main.ts looks like

**Comment by ocombe** [comment]
Hello, I have updated the documentation recently, so maybe you were using the old code.

Here is the current example:

```
// Load `$localize` onto the global scope - used if i18n tags appear in Angular templates.
import '@angular/localize/init';

import { loadTranslations } from '@angular/localize';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { getTranslations, ParsedTranslationBundle } from '@locl/core';

getTranslations('/assets/i18n/fr.json').then(
  (data: ParsedTranslationBundle) => {
    loadTranslations(data.translations);
    import('./app/app.module').then(module => {
      platformBrowserDynamic()
        .bootstrapModule(module.AppModule)
        .catch(err => console.error(err));
    });
  }
);
```

You can notice that we are loading the app module as a dynamic import after the translations have been loaded. The reason for that is that, in AOT mode, $localize calls are defined as constants outside of the template creation. This means that $localize will try to find the translations as soon as the module is imported, which would be when the app is loaded in the case of a regular import. By using a dynamic import we ensure that the translations are loaded before the module.

**Comment by ocombe** [comment]
actually I just looked at your `main`, you're using the current code, except for:
```
import { AppModule } from './app/';
```

Remove that line, and it'll work fine

**Comment by shral** [comment]
Thank you a lot for the response!
