### ISSUE TITLE
npx locl extract not aggregating source files into one translation file

### ISSUE THREAD

**Issue by johannks** [loclapp/locl#16]
I'm trying out `locl extract` using @locl/cli v0.0.1-beta.6, but am unable to generate a single extracted file according to "If the given path is a file, it will aggregate the translations of all the source files into one translation file."

My goal is to replace:
```
ngx-extractor -i "src/**/*.ts" -f xlf -o src/locale/_source.en.xlf
```
with:
```
npx locl extract -s=dist/**/*.js -f=xlf -o=src/locale/_source.en.xlf
```
but I keep ending up with multiple files:
```
Extracting translations from "dist/**/*"
  Generated file "[...]\src\locale\_source/0.3a3f18a0f1d60f21cfab.en.xlf"
  Generated file "[...]\src\locale\_source/10.16cf2e323fc2e6a55687.en.xlf"
  Generated file "[...]\src\locale\_source/11.47c90a031697c06dcb2d.en.xlf"
  Generated file "[...]\src\locale\_source/12.d90362b8cc6cf9184f5d.en.xlf"
  Generated file "[...]\src\locale\_source/3.fe802cf4f008cccac82c.en.xlf"
  Generated file "[...]\src\locale\_source/8.d21ac796b0c09608c89a.en.xlf"
  Generated file "[...]\src\locale\_source/9.e6ad1eaa6162368d3ec8.en.xlf"
  Generated file "[...]\src\locale\_source/main.468caea773954c4d79b6.en.xlf"
```
Thanks for looking into this and providing excellent tools.

**Comment by johannks** [comment]
FYI, above, I was running the commands in the powershell on vscode (Win10). When testing with an npm script:
```
"locl-extract": "ng build --prod && npx locl extract -s=dist/**/*.js -f=xlf -o=src/locale/_source.en.xlf"
```
a single file was generated:
```
Extracting translations from "dist/**/*.js"
  Generated file "[...]\src\locale\_source.en.xlf"
```

**Comment by plutosimple** [comment]
I'm seeing this as well in 0.0.1-beta.9.  For me, it aggregated correctly when the built project had "enableIvy" = true, but not with "enableIvy" = false.

**Comment by ocombe** [comment]
Locl only works with ivy. If you don't enable ivy, you might be able to extract translations from your code, but not from the templates.
Do you have ivy enabled @johannks ?

**Comment by johannks** [comment]
I'm using Angular 9, and haven't set "enableIvy" = false, so I assume I am.

**Comment by richard-ob** [comment]
I just ran into this issue. It appears to be just that you need to wrap the output path in double quotes on Windows.

For example, the command above would be:
`ngx-extractor -i "src/**/*.ts" -f xlf -o="src/locale/_source.en.xlf"`

@ocombe: might be worth mentioning this as a "gotcha". I think Locl only sees the folder part of the path, so its doing the expected multi-file behaviour.

**Comment by ocombe** [comment]
Good catch @richard-ob thanks, looks like it's a limitation of yargs which I use to parse commands
