### ISSUE TITLE
Extraction fails with `unknown: Unepected reserved word 'enum'`

### ISSUE THREAD

**Issue by shu-mutou** [loclapp/locl#20]
When I ran following command, extraction failed as title.
`npx locl extract -f=xlf -s=src/frontend/**/*.ts -o=i18n/ts.xlf -l=en`

Ref: https://github.com/kubernetes/dashboard/issues/4871

**Comment by shu-mutou** [comment]
Sorry, this seems to be my mistake.

**Comment by ocombe** [comment]
Hello, locl works on compiled files (you have to build the project with aot & ivy), not on source files, that's probably why you have this error. It doesn't support typescript files, just javascript (just like the localize package from Angular).
