### ISSUE TITLE
Warning: Entry point '@locl/cli' contains deep imports into 

### ISSUE THREAD

**Issue by DanielHabenicht** [loclapp/locl#23]
While compiling Angular with `ngcc` the following warning is produced: 

```bash
Warning: Entry point '@locl/cli' contains deep imports into 'C:/Develop/project/node_modules/@angular/localize/src/tools/src/diagnostics'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
```
It may be solved by https://github.com/angular/angular/issues/35615 is a solution (Add `ngcc.config.js`)

**Comment by Tzahi12345** [comment]
Experiencing the exact same issue! I tried that solution and it didn't work. Wonder what is causing it...

**Comment by DanielHabenicht** [comment]
@Tzahi12345 did you add it to the `@locl/cli` package in you `node_modules`?

**Comment by ocombe** [comment]
I will update the code to avoid the deep import, it's not used for something important anyway

**Comment by DanielHabenicht** [comment]
Thanks!
