### ISSUE TITLE
Angular 9.1.4+ and locl/cli (beta.v7) stopped to extract strings

### ISSUE THREAD

**Issue by tomascubeek** [loclapp/locl#27]
Hello,

I know you are in beta with your cli, but there seems to some change on angular side since v9.1.4 (few hours ago) and @locl/cli is not able to extract all occurences of $localize (in my case just one from many). I'm using es2015 output format with ivy and aot (as it used to work before). Is it known issue? Will that be fixed on extractor side or we should somehow change our approach?

**Comment by ocombe** [comment]
Hello, thanks for the report, let me check if something changed on the Angular side, I'll get back to you!

**Comment by ocombe** [comment]
Yes, looks like the internal extraction method was changed (that's the problem when you use private internal APIs!).
Fixing it.

**Comment by ocombe** [comment]
Fixed in beta 8! Thanks for the report!

**Comment by tomascubeek** [comment]
Awesome, thanks!

**Comment by ocombe** [comment]
ahah looks like the deep import warning message is back though, I'll have to fix it :(

**Comment by ocombe** [comment]
fixed in beta 9! sorry about that
