### ISSUE TITLE
es5 - ERROR TypeError: String.prototype.valueOf requires that 'this' be a String

### ISSUE THREAD

**Issue by plutosimple** [loclapp/locl#29]
This happens when you set the tsConfig buildTarget to es5 and then `npm run start.demo`

The compiler fix is to override the valueOf method in LoclString to call the ToString()

```
  valueOf(): string {
    return this.toString();
  }
```

I'm not too familiar with how this library works so I don't know if the above fix would have any side-effects.

**Comment by ocombe** [comment]
oh thanks, good catch!

**Comment by richard-ob** [comment]
Just to confirm, this is has yet to have a fix applied? 

Ran into the same issue here on the latest (`1.0.0-rc.1`).

**Comment by plutosimple** [comment]
I forked the code here and applied a fix that doesn't require upgrading to Angular 10
https://github.com/plutosimple/locl

**Comment by danylobilokha** [comment]
I get this issue with 
- "@locl/core": "1.0.0-rc.1",
- "@locl/cli": "1.0.0",
 
and  "@angular/*": "12.1.1",
