### ISSUE TITLE
Babel error when running nix locl extract

### ISSUE THREAD

**Issue by tooPak** [loclapp/locl#33]
I'm trying to extract my translations as I did before in Angular 8 with @ngx-translate/i18n-polyfill.

I get the following error: `unknown: Support for the experimental syntax 'decorators-legacy' isn't currently enabled:
`
The error is appearing at the component decorator (@Component).

I did all necessary changes from Angular 8 to 9 changing my old polyfills to $localize and the application is compiling and running fine.

**Comment by ocombe** [comment]
As explained in https://github.com/loclapp/locl/issues/11, you need to run the extractor on the dist folder (on the files compiled with aot), not on the source files.
Let me know if that was not the issue in your case.
