### ISSUE TITLE
Xliff 2 Invalid

### ISSUE THREAD

**Issue by napei** [loclapp/locl#38]
Files that are generated using `locl extract` with format set to `xlf2` are not valid as per the schema. The root `file` attribute generates without an `id` attribute which is required by the schema. This causes problems importing into a service like crowdin, where it will fail to import if the schema is not valid.

[http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#file](http://docs.oasis-open.org/xliff/xliff-core/v2.0/xliff-core-v2.0.html#file)

Validator: [https://okapi-lynx.appspot.com/validation](https://okapi-lynx.appspot.com/validation)

### Examples 

**Valid:** 

```xml
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en" trgLang="en">
  <file id="1234">
    <unit id="6962311588473741961">
      <segment>
        <source>Search filter</source>
        <target>Search filter</target>
      </segment>
    </unit>
  </file>
</xliff>
```

**Invalid (generated by `locl extract`):**

```xml
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en" trgLang="en">
  <file>
    <unit id="6962311588473741961">
      <segment>
        <source>Search filter</source>
        <target>Search filter</target>
      </segment>
    </unit>
  </file>
</xliff>
```

For reference, this is what `ng xi18n --format xlf2` does:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="2.0" xmlns="urn:oasis:names:tc:xliff:document:2.0" srcLang="en">
  <file original="ng.template" id="ngi18n">
    ...
```

**Comment by ocombe** [comment]
Thanks for the report! I didn't know that, and you're right, the Angular compiler does indeed add the id attribute
