### ISSUE TITLE
Bug on stackblitz demo

### ISSUE THREAD

**Issue by phinheiro** [loclapp/locl#39]
This error was shown to me while I tried to view the demo on stackblitz, so I decided to report it for you

![image](https://user-images.githubusercontent.com/54939186/89177407-cc0a6a00-d561-11ea-81fa-81db6e11b87a.png)

It has ocurred after the stackblitz tried to compile the application and start dev server,

**Comment by ocombe** [comment]
Thanks! Demo updated!
