### ISSUE TITLE
Improvement: Error message for wrong filename

### ISSUE THREAD

**Issue by JohannesHoppe** [loclapp/locl#4]
I spend a while trying to figure out what I did wrong:

```
npx locl convert -s=XXX -f=json -o=test.json
```

Error message:
`Cannot read property 'locale' of undefined`

TODO:
Check for file existence, exit with meaningful error message.

Many thanks for your useful tool! 👍

**Comment by ocombe** [comment]
Hello, do you have the line of the error, or the file that you wanted to convert?
Or is it just that the file doesn't exist?

**Comment by JohannesHoppe** [comment]
Exactly, file does not exist (or typo in name).

**Comment by ocombe** [comment]
Thanks, I'll add an error handler for that :)
