### ISSUE TITLE
Error on trying to convert .xlf to .json

### ISSUE THREAD

**Issue by jacobbowdoin** [loclapp/locl#7]
I'm running this command: 
`npx locl convert -s=src/locale/es/messages.xlf -f=json -o=src/locale/es/messages.json`

In an Angular 8 repo with an XLF file created via `ng extract`, then translated using Crowdin. I'm looking to convert it to the json format but am receiving an error message:
`Cannot read property 'locale' of undefined`

Here is the beginning of my messages.xlf file is like if it helps:
```
<?xml version="1.0" encoding="UTF-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" version="1.2">
  <file source-language="en" datatype="plaintext" original="ng2.template" target-language="es-ES">
    <body>
      <trans-unit id="TD" datatype="html" approved="yes">
        <source>Talking Dictionaries</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/header/header.component.html</context>
          <context context-type="linenumber">4</context>
        </context-group>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/home/home/home.component.html</context>
          <context context-type="linenumber">139</context>
        </context-group>
        <target state="final">Diccionarios hablados</target>
      </trans-unit>
```

**Comment by ocombe** [comment]
Hello, this error message usually happens when the script is unable to find the file (yes I know, it's not explicit and I need to add a proper error message).
My guess is that `-s=src/locale/es/messages.xlf` is not correct, maybe try with `-s=./src/locale/es/messages.xlf`, or check if you're in the correct folder?

**Comment by jacobbowdoin** [comment]
Using `-s=./src/locale/es/messages.xlf` returns another error:
```
TypeError: compiler_1.XmlParser is not a constructor
    at Xliff1TranslationParser.parse (C:\Apps\talking-dictionaries\node_modules\@locl\cli\src\cmds\convert\translation_parsers\xliff1_translation_parser.js:30:27)
```
Should I give more context?

**Comment by ocombe** [comment]
Yes, that would be great!
Can you send me the xlf file? You can send it to olivier@locl.app if you don't want to post it publicly here

**Comment by ocombe** [comment]
Ok so I tried to convert your file and it worked fine for me, given the line of the error, I'd say that your version of `@angular/compiler` doesn't work with `@locl/cli`, could you tell me which version you use?
In any case I need to update the list of dependencies for the lib

**Comment by jacobbowdoin** [comment]
I have version 8.2.15 of `@angular/compiler`. It sounds like I should just create a new angular project with the latest version of the CLI and use that project to convert my file. But I hope my situation can help you improve the project for others (it's a great one!).

 ```
 "dependencies": {
    "@angular/animations": "^8.2.14",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.2.14",
    "@angular/compiler": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/forms": "^8.2.14",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/pwa": "^0.803.20",
    "@angular/router": "^8.2.14",
    "@angular/service-worker": "^8.2.14",
    "rxjs": "^6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.20",
    "@angular/cli": "^8.3.20",
    "@angular/compiler-cli": "^8.2.14",
    "@angular/language-service": "^8.2.14",
    "@locl/cli": "0.0.1-beta.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "^5.20.1",
    "typescript": "~3.5.3"
  }
```

**Comment by ocombe** [comment]
Ah yes, it makes sense then. Locl only works with Angular v9 (any RC above rc-7 should work).
I'll publish a fix to include the compiler as a peer-dependency!

**Comment by ocombe** [comment]
The new beta 4 includes the correct peer dependencies.
